### ISSUE TITLE
Extract issues from Yuchen's HRM submissions

### ISSUE THREAD

**Issue by iangow** [iangow/se_core#12]
@Yvonne-Han This should probably be assigned to @yuchenliu4, but he hasn't joined this repository yet. Basically, we need to go through Yuchen's HRM submission and create GitHub issues for each of the problems that he raised there (e.g., malformed roles, improperly parsed files).

**Comment by Yvonne-Han** [comment]
@iangow Got it. I will follow up on this after Yuchen is back. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Yvonne-Han** [comment]
Done. See newly created issues #13, #14, #15.
