### ISSUE TITLE
Test update code

### ISSUE THREAD

**Issue by iangow** [iangow/se_core#2]
@danielacarrasco 

You would need to change the code in `update_se.sh` to use your user ID (`carrascod`) in place of mine (`iangow`).

It is probably a good idea to do something similar to [this](https://github.com/iangow-public/wrds_pg#3-a-wrds-id) to avoid having to enter passwords. Let's discuss on Tuesday.

**Comment by danielacarrasco** [comment]
I was able to download the files. Is this expected to fix [this](https://github.com/iangow/se_features/issues/5#issuecomment-439686672) ?

For now I am "translating" this project into python.

**Comment by iangow** [comment]
@danielacarrasco I can now connect **from `10.101.13.99`** to the server holding the original XML files (`45.113.235.201`). Please test that you can do the same.

```
igow@igow-z640:~$ ssh iangow@45.113.235.201
-------------------------------------------------------------------------------------
  NeCTAR Ubuntu 16.04.4 LTS x86_64
  Image details and information is available at
  https://support.nectar.org.au/support/solutions/articles/6000106269-image-catalog
-------------------------------------------------------------------------------------

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
New release '18.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Tue Nov 20 21:13:07 2018 from 10.101.13.99
iangow@sftp-resplat:~$ exit
```

**Comment by iangow** [comment]
I think I will take a simpler approach. See #6.
